// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "location-table-fmcenv",
            "region": "us-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "api8b99ff04",
            "endpoint": "https://n0gozc7dn1.execute-api.us-west-2.amazonaws.com/fmcenv",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
