// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "findmycar-project",
            "region": "us-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "findmycar",
            "endpoint": "https://3vvi18cocg.execute-api.us-west-2.amazonaws.com/project",
            "region": "us-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-west-2:7c54c2da-fafb-473b-b58b-c4b09e05e5bc",
    "aws_cognito_region": "us-west-2",
    "oauth": {},
    "aws_mobile_analytics_app_id": "aec69c2e8d154dc1884618db96c8cdf4",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
